# Generated by Django 2.2.7 on 2019-11-19 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20191119_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
                ('specialist_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='account.Specialist')),
                ('specialist_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='account.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed')], default='booked', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Specialist')),
            ],
        ),
    ]
